name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below to help us understand your idea.

  - type: textarea
    id: mission
    attributes:
      label: Mission / Outcome
      description: What problem does this feature solve? What is the desired outcome?
      placeholder: |
        Example: Enable users to track AI usage patterns across their projects, helping them understand where AI tools provide the most value.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope & Out of Scope
      description: What should be included in this feature? What should NOT be included?
      placeholder: |
        **In Scope:**
        - Basic analytics dashboard
        - Export to CSV
        
        **Out of Scope:**
        - Real-time streaming
        - Third-party integrations
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Links & Context
      description: Provide any relevant links, references, or additional context
      placeholder: |
        - Related issue: #123
        - Documentation: https://...
        - Reference implementation: https://...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might be helpful

  - type: checkboxes
    id: ai_assistance
    attributes:
      label: AI Assistance (optional)
      description: Did you use AI tools to help create this issue?
      options:
        - label: ChatGPT (planning / wording)
        - label: GitHub Copilot (editor)
        - label: Copilot Agent (automation)
        - label: Other AI tool (please specify in Additional Information)
